// Função para simular a chamada da API
export const fetchGroupData = () => {
  return [
    {
      id: 1,
      title: "Grupo da Solidariedade 1",
      donationsPerDay: 15,
      description: "Este grupo é dedicado a fornecer suporte alimentar para famílias necessitadas na região de Registro-SP. Junte-se a nós para fazer a diferença!",
      address: "Rua do Moinho, 232, Registro-SP",
      image: "https://via.placeholder.com/150/0000FF/808080?text=Grupo+1",
      banner: "https://via.placeholder.com/770x280/0000FF/FFFFFF?text=Banner+Grupo+1",
      users: [
        "https://via.placeholder.com/50/FF0000/FFFFFF?text=U1",
        "https://via.placeholder.com/50/00FF00/FFFFFF?text=U2",
        "https://via.placeholder.com/50/0000FF/FFFFFF?text=U3",
        "https://via.placeholder.com/50/FFFF00/FFFFFF?text=U4",
        "https://via.placeholder.com/50/FF00FF/FFFFFF?text=U5",
        "https://via.placeholder.com/50/00FFFF/FFFFFF?text=U6",
        "https://via.placeholder.com/50/000000/FFFFFF?text=U7",
      ],
      solicited: false,
    },
    {
      id: 2,
      title: "Grupo de Apoio à Educação",
      donationsPerDay: 10,
      description: "Nosso objetivo é melhorar a educação nas comunidades carentes, fornecendo materiais escolares e apoio educacional.",
      address: "Avenida Principal, 100, São Paulo-SP",
      image: "https://via.placeholder.com/150/FF0000/808080?text=Grupo+2",
      banner: "https://via.placeholder.com/770x280/FF0000/FFFFFF?text=Banner+Grupo+2",
      users: [
        "https://via.placeholder.com/50/0000FF/FFFFFF?text=U1",
        "https://via.placeholder.com/50/00FF00/FFFFFF?text=U2",
        "https://via.placeholder.com/50/FF0000/FFFFFF?text=U3",
        "https://via.placeholder.com/50/FFFF00/FFFFFF?text=U4",
        "https://via.placeholder.com/50/00FFFF/FFFFFF?text=U5",
      ],
      solicited: false,
    },
    {
      id: 3,
      title: "Grupo de Apoio à Saúde",
      donationsPerDay: 8,
      description: "Nosso grupo oferece assistência médica gratuita para pessoas em situação de vulnerabilidade social.",
      address: "Rua das Flores, 50, Belo Horizonte-MG",
      image: "https://via.placeholder.com/150/00FF00/808080?text=Grupo+3",
      banner: "https://via.placeholder.com/770x280/00FF00/FFFFFF?text=Banner+Grupo+3",
      users: [
        "https://via.placeholder.com/50/FF0000/FFFFFF?text=U1",
        "https://via.placeholder.com/50/00FF00/FFFFFF?text=U2",
        "https://via.placeholder.com/50/0000FF/FFFFFF?text=U3",
        "https://via.placeholder.com/50/FFFF00/FFFFFF?text=U4",
        "https://via.placeholder.com/50/FF00FF/FFFFFF?text=U5",
        "https://via.placeholder.com/50/00FFFF/FFFFFF?text=U6",
      ],
      solicited: false,
    },
    {
      id: 4,
      title: "Grupo de Recolhimento de Roupas",
      donationsPerDay: 12,
      description: "Coletamos roupas usadas e distribuímos para famílias em situação de rua e em abrigos.",
      address: "Praça Central, 20, Curitiba-PR",
      image: "https://via.placeholder.com/150/FFFF00/808080?text=Grupo+4",
      banner: "https://via.placeholder.com/770x280/FFFF00/FFFFFF?text=Banner+Grupo+4",
      users: [
        "https://via.placeholder.com/50/FF0000/FFFFFF?text=U1",
        "https://via.placeholder.com/50/00FF00/FFFFFF?text=U2",
        "https://via.placeholder.com/50/0000FF/FFFFFF?text=U3",
        "https://via.placeholder.com/50/FFFF00/FFFFFF?text=U4",
        "https://via.placeholder.com/50/FF00FF/FFFFFF?text=U5",
        "https://via.placeholder.com/50/00FFFF/FFFFFF?text=U6",
        "https://via.placeholder.com/50/000000/FFFFFF?text=U7",
      ],
      solicited: false,
    },
    {
      id: 5,
      title: "Grupo de Apoio Psicológico",
      donationsPerDay: 7,
      description: "Fornecemos apoio psicológico gratuito para pessoas que passam por dificuldades emocionais.",
      address: "Rua da Paz, 10, Rio de Janeiro-RJ",
      image: "https://via.placeholder.com/150/FF00FF/808080?text=Grupo+5",
      banner: "https://via.placeholder.com/770x280/FF00FF/FFFFFF?text=Banner+Grupo+5",
      users: [
        "https://via.placeholder.com/50/FF0000/FFFFFF?text=U1",
        "https://via.placeholder.com/50/00FF00/FFFFFF?text=U2",
        "https://via.placeholder.com/50/0000FF/FFFFFF?text=U3",
        "https://via.placeholder.com/50/FFFF00/FFFFFF?text=U4",
        "https://via.placeholder.com/50/FF00FF/FFFFFF?text=U5",
      ],
      solicited: false,
    },
  ];
};